/*
 * This file is generated by jOOQ.
*/
package com.example.dto.tables;


import com.example.dto.Indexes;
import com.example.dto.Keys;
import com.example.dto.TestTemp;
import com.example.dto.tables.records.AlpakkaSlickJavadslTestUsersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlpakkaSlickJavadslTestUsers extends TableImpl<AlpakkaSlickJavadslTestUsersRecord> {

    private static final long serialVersionUID = -274493758;

    /**
     * The reference instance of <code>test_temp.alpakka_slick_javadsl_test_users</code>
     */
    public static final AlpakkaSlickJavadslTestUsers ALPAKKA_SLICK_JAVADSL_TEST_USERS = new AlpakkaSlickJavadslTestUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlpakkaSlickJavadslTestUsersRecord> getRecordType() {
        return AlpakkaSlickJavadslTestUsersRecord.class;
    }

    /**
     * The column <code>test_temp.alpakka_slick_javadsl_test_users.ID</code>.
     */
    public final TableField<AlpakkaSlickJavadslTestUsersRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test_temp.alpakka_slick_javadsl_test_users.NAME</code>.
     */
    public final TableField<AlpakkaSlickJavadslTestUsersRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>test_temp.alpakka_slick_javadsl_test_users</code> table reference
     */
    public AlpakkaSlickJavadslTestUsers() {
        this(DSL.name("alpakka_slick_javadsl_test_users"), null);
    }

    /**
     * Create an aliased <code>test_temp.alpakka_slick_javadsl_test_users</code> table reference
     */
    public AlpakkaSlickJavadslTestUsers(String alias) {
        this(DSL.name(alias), ALPAKKA_SLICK_JAVADSL_TEST_USERS);
    }

    /**
     * Create an aliased <code>test_temp.alpakka_slick_javadsl_test_users</code> table reference
     */
    public AlpakkaSlickJavadslTestUsers(Name alias) {
        this(alias, ALPAKKA_SLICK_JAVADSL_TEST_USERS);
    }

    private AlpakkaSlickJavadslTestUsers(Name alias, Table<AlpakkaSlickJavadslTestUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlpakkaSlickJavadslTestUsers(Name alias, Table<AlpakkaSlickJavadslTestUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return TestTemp.TEST_TEMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ALPAKKA_SLICK_JAVADSL_TEST_USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AlpakkaSlickJavadslTestUsersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ALPAKKA_SLICK_JAVADSL_TEST_USERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlpakkaSlickJavadslTestUsersRecord> getPrimaryKey() {
        return Keys.KEY_ALPAKKA_SLICK_JAVADSL_TEST_USERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlpakkaSlickJavadslTestUsersRecord>> getKeys() {
        return Arrays.<UniqueKey<AlpakkaSlickJavadslTestUsersRecord>>asList(Keys.KEY_ALPAKKA_SLICK_JAVADSL_TEST_USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlpakkaSlickJavadslTestUsers as(String alias) {
        return new AlpakkaSlickJavadslTestUsers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlpakkaSlickJavadslTestUsers as(Name alias) {
        return new AlpakkaSlickJavadslTestUsers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlpakkaSlickJavadslTestUsers rename(String name) {
        return new AlpakkaSlickJavadslTestUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlpakkaSlickJavadslTestUsers rename(Name name) {
        return new AlpakkaSlickJavadslTestUsers(name, null);
    }
}
