/*
 * This file is generated by jOOQ.
*/
package com.example.dto;


import com.example.dto.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test_temp</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_UK_DNQ7R8JCMLFT7L8L4J79L1H74 = Indexes0.USER_UK_DNQ7R8JCMLFT7L8L4J79L1H74;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_UK_DNQ7R8JCMLFT7L8L4J79L1H74 = Internal.createIndex("UK_dnq7r8jcmlft7l8l4j79l1h74", User.USER, new OrderField[] { User.USER.EMAIL }, true);
    }
}
