/*
 * This file is generated by jOOQ.
*/
package com.example.dto;


import com.example.dto.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test_temp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_temp.user</code>.
     */
    public static final User USER = com.example.dto.tables.User.USER;
}
