/*
 * This file is generated by jOOQ.
*/
package com.example.dto;


import com.example.dto.tables.AlpakkaSlickJavadslTestUsers;
import com.example.dto.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestTemp extends SchemaImpl {

    private static final long serialVersionUID = 1554809217;

    /**
     * The reference instance of <code>test_temp</code>
     */
    public static final TestTemp TEST_TEMP = new TestTemp();

    /**
     * The table <code>test_temp.alpakka_slick_javadsl_test_users</code>.
     */
    public final AlpakkaSlickJavadslTestUsers ALPAKKA_SLICK_JAVADSL_TEST_USERS = com.example.dto.tables.AlpakkaSlickJavadslTestUsers.ALPAKKA_SLICK_JAVADSL_TEST_USERS;

    /**
     * The table <code>test_temp.user</code>.
     */
    public final User USER = com.example.dto.tables.User.USER;

    /**
     * No further instances allowed
     */
    private TestTemp() {
        super("test_temp", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AlpakkaSlickJavadslTestUsers.ALPAKKA_SLICK_JAVADSL_TEST_USERS,
            User.USER);
    }
}
