/*
 * This file is generated by jOOQ.
*/
package com.example.dto.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1508947608;

    private Integer userId;
    private String  account;
    private String  name;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.account = value.account;
        this.name = value.name;
    }

    public User(
        Integer userId,
        String  account,
        String  name
    ) {
        this.userId = userId;
        this.account = account;
        this.name = name;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(account);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
